# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160902_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_sale',
            field=models.IntegerField(default=0),
        ),
    ]
