# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField()),
                ('transaction_hash', models.CharField(max_length=100)),
                ('is_validated', models.BooleanField()),
                ('product', models.ManyToManyField(to='product.Product')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopper.Shopper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
