# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactiondetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ManyToManyField(related_name='transaction', through='transaction.TransactionDetails', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_transaction', to='product.Product'),
        ),
    ]
