# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20160902_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_hash',
            new_name='payment_id',
        ),
    ]
