# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20160902_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='product.Product'),
        ),
    ]
