# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
